# Generated by Django 6.0.2 on 2026-08-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='customers/photos/'),
        ),
    ]
